### ISSUE TITLE
Can not run desktop sample on windows 7 x64

### ISSUE THREAD

**Issue by cjsbox-xx** [opensciencemap/vtm#152]
Hi!
Trying to run sample on win7 x64 using gradlew :vtm-desktop:run and getting the following exception:
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't
load shared library 'vtm-jni64.dll' for target: Windows 7, 64-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.j
ava:117)
        at org.oscim.gdx.GdxMapApp.init(GdxMapApp.java:38)
        at org.oscim.gdx.GdxMapApp.main(GdxMapApp.java:48)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for e
xtraction: vtm-jni64.dll
        at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoad
er.java:126)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoad
er.java:261)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.j
ava:115)
        ... 2 more
```

**Comment by kaimw** [comment]
you should build jni first
